### ISSUE TITLE
Batch import of ideas and users

### ISSUE THREAD

**Issue by crisptrutski** [votepourca/geoforms#13]
Reads CSV files, could run as a CLI task

**Comment by crisptrutski** [comment]
@votepourca do you have a sample CSV already, or can I create their format?

**Comment by votepourca** [comment]
You could do that, perfect! I will ajust my csvs according to your template (ideas, users)

**Comment by crisptrutski** [comment]
Added in f6a917689f0148b47982a30a133d58f3bc993d69
