### ISSUE TITLE
Additional form validation

### ISSUE THREAD

**Issue by crisptrutski** [votepourca/geoforms#14]
- [x] Idea has a title
- [x] Idea has a category
- [x] Idea title is unique to district(s) (see #12)
- [ ] ~~Idea form asserts that user has identified themselves (see #5)~~

**Comment by votepourca** [comment]
We would need to allow adding an idea only when user required fields are provided. We won't allow an idea to be added by anonymous people.

**Comment by crisptrutski** [comment]
From #12 will assert that idea title is unique

**Comment by crisptrutski** [comment]
Not going to validate user identification in form, but will rather defer creation. 

This should complete idea validation.
