### ISSUE TITLE
Reverse toggle districts, do not display all steps when no districts toggle

### ISSUE THREAD

**Issue by votepourca** [votepourca/geoforms#16]
I think if we want to embed our app, we should ask people to select one (or more) districts, while not displaying other steps. By default, no district are selected. When you do select the first, we can see step 2+. Or better approach if you have any ideas. I find a bit annoying to start by untoggling district. What do you think Chris?

**Comment by crisptrutski** [comment]
Makes total sense
- [x] Default to no selected districts
- [x] Hide sections 2 - 4 unless a district is selected

**Comment by crisptrutski** [comment]
Should be taken care of!

**Comment by votepourca** [comment]
Nice to have 
- [x] Sort district in step one by number of ideas. Put number of ideas in paratheses

Manhattan (8)  Brooklyn (4)  , etc.

**Comment by crisptrutski** [comment]
Last point handled in 8782b0b9387cc18fed47cecfbbf7ca1702355f9c
