### ISSUE TITLE
Form bindings are coupled too strongly to layout and structure

### ISSUE THREAD

**Issue by crisptrutski** [votepourca/geoforms#3]
The reagent-forms vectors do not compose fully as reagent components would - you cannot use the `[component-function arg1 arg2]` form within. This makes reuse and composition harder.

For this reason the form hiccup data should be bound as tightly as possible, so call `bind-fields` separately for each main chunk.

**Comment by crisptrutski** [comment]
The idea is now created in a separate form, with a separate atom. But it's nested inside (bad form).

Note that there's nothing to stop binding multiple templates to the same atom, so each "section" could create it's own bindings.

Note that I had trouble (due to late loading of options?) of binding the category select box with reagent-forms, so just dropped to vanilla React there.

**Comment by votepourca** [comment]
yes that is not a requirement to use reagent-forms. I like the idea of reusable components. I follow you.

**Comment by crisptrutski** [comment]
OK, closing this at it'll happen as an asside when layout is polished
