### ISSUE TITLE
Aditional language support

### ISSUE THREAD

**Issue by crisptrutski** [votepourca/geoforms#8]
- [x] Config option to switch language
- [x] Static tites are language sensitive
- [x] District names and categories are language sensitive
- ~~Will the site have a "switch-language" control?~~
- ~~Will ideas be stored separately per language?~~

**Comment by crisptrutski** [comment]
May be worth doing this more formally with something like https://github.com/ptaoussanis/tower

**Comment by votepourca** [comment]
Cool! If it can be quickly implemented, yes, for sure!
It looks pretty neat!

**Comment by crisptrutski** [comment]
Not doable to include Tower this evening, I'm not familiar enough with it. But perhaps in future

**Comment by crisptrutski** [comment]
I have not translated all static text, but the pattern should be simple enough for you to extend.

Not much text yet, so think it's OK to just bundle all languages for now.

**Comment by crisptrutski** [comment]
@leontalbot perhaps taking districts and categories out of firebase is worthwhile for translating. also decreases initial load a bit

**Comment by votepourca** [comment]
yes

**Comment by crisptrutski** [comment]
This should all be covered, but feel free to reopen with issues
